name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your main branch name if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Deploy
        run: |
          # Build your website here (e.g., npm install, npm build, etc.)
          # Replace this with your build commands
          echo "Build your website here"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAT }}
          publish_dir: ./build  # Replace with the directory containing your built website

